name: 🐛 Bug report
description: If something isn't working as expected, please report a bug here.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        *Please fill this form with as much information as possible!*
  - type: textarea
    id: what-did
    attributes:
      label: Describe the bug.
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem.
      description: Please provide me with precise step by step instructions on how to reproduce the bug.
      value: |
        1. Go to .... 
        2. Press ....
        3. ...
    validations:
      required: true
  - type: textarea
    id: what-should
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: sysinfo
    attributes:
      label: System info
      description: Information about your system and the versions that were used.
      value: |
        * Extension version:
        * OS:
        * SD-WebUI version:
        * Python:
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Console logs
      description: Please provide **full** cmd/terminal logs from the moment you started UI to the end of it, after your bug happened. If it's very long, provide a link to pastebin or similar service.
      render: Shell
    validations:
      required: true
  - type: textarea
    id: misc
    attributes:
      label: Additional information
      description: Please provide me with any relevant additional info or context.
